APP_NAME := "traefik-authproxy"

LOCAL_OIDC := "http://mock-oidc.localhost"
LOCAL_OIDC_DOCKER := "http://host.docker.internal:8080"
LOCAL_CLIENT_ID := "audit-service-client"
LOCAL_CLIENT_SECRET := "mTEqlt1dDzcVyEOzFjBZV4X8jvEkaQnc"

# build application
docker:
    docker build -t {{APP_NAME}}:latest .
    docker tag {{APP_NAME}}:latest localhost:5005/{{APP_NAME}}:latest
    docker push localhost:5005/{{APP_NAME}}:latest
    docker images | grep "{{APP_NAME}}"

# run docker image
run: docker
    docker run -p 8081:8081 \
      -e OIDC_DISCOVERY_URL="{{LOCAL_OIDC_DOCKER}}/labs64io/.well-known/openid-configuration" \
      -e OIDC_AUDIENCE="account" \
      -e CERBOS_URL="http://host.docker.internal:3592" \
      -e ROUTES_DIR="/home/l64user/routes" \
      -e STATIC_ROUTES_FILE="/home/l64user/static_routes.yaml" \
      -v $(pwd)/static_routes.yaml:/home/l64user/static_routes.yaml \
      {{APP_NAME}}:latest

# open documentation
docu:
    open "http://localhost:8081/redoc"
    open "http://localhost:8081/docs"

# check updates
check-updates:
    python3 -m venv temp_env
    temp_env/bin/python3 -m pip install --upgrade pip
    temp_env/bin/pip install -r requirements.txt
    temp_env/bin/pip list --outdated
    rm -rf temp_env
    docker scout cves {{APP_NAME}}:latest

# open OIDC well-known configuration
test-show-wellknown:
    open "{{LOCAL_OIDC}}/labs64io/.well-known/openid-configuration"

# generate JWT token
test-generate-jwt-token:
    curl --location --request POST '{{LOCAL_OIDC}}/labs64io/token' \
    --header 'Content-Type: application/x-www-form-urlencoded' \
    --data-urlencode 'grant_type=client_credentials' \
    --data-urlencode 'client_id={{LOCAL_CLIENT_ID}}' \
    --data-urlencode 'client_secret={{LOCAL_CLIENT_SECRET}}' \
    --data-urlencode 'scope=admin'
