/api/v1/admin:
  - admin-role

/api/v1/auditflow:
  - admin-role
  - auditflow-role
  - default-roles-labs64io

/api/v1/ecommerce:
  - admin-role
  - ecommerce-role
  - default-roles-labs64io

/public: []
/v3/api-docs: []
/actuator: []
/health: []
