# -- public paths (auth proxy internal endpoints)
/auth: []
/health: []
/reload: []

# -- public paths (downstream service endpoints)
/public: []
/docs: []
/swagger-ui: []
/v3/api-docs: []
/actuator: []

# -- protected paths
/path1:
  - role1
  - role2
/path2:
  - role2
