name: Labs64.IO - API Gateway - Publish Docker

permissions:
  contents: read
  packages: write

on:
  release:
    types: [created]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file ./api-gateway-be/pom.xml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get release tag name
        id: get_release_tag
        run: echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./traefik-authproxy
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: |
            labs64/traefik-authproxy:latest
            labs64/traefik-authproxy:${{ steps.get_release_tag.outputs.RELEASE_TAG }}
          cache-from: type=gha,scope=${{ github.workflow }}-traefik-authproxy
          cache-to: type=gha,mode=max,scope=${{ github.workflow }}-traefik-authproxy
